# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f022a19f51367e2b4ea5f1979ec90e448ef02ef1ebbd8de8d2f6f1b2b565cb51107503d7bcc9d4e26034e3d833921223f4c71df6ec7e58eb94aa9fdde6edbb

test:
  secret_key_base: e5550954cf6383e13ea3a37a97c4155811512086e1cee59a17e32ea2fb3f08812ce467ac940e5e9680d944517847b67c43d28f939dc34ef2cf24c575b7d812c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
